---
- name: extract artifact
  become: yes
  unarchive:
    src: files/artifact.tar.gz
    dest: .

- name: start server
  become: yes
  become_method: sudo
  become_user: root 
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
    pm2 start dist/main.js --name node-app